src/TheWorld/Models/Trip.cs
using System;
using System.Collections.Generic;

namespace TheWorld.Models
{
    public class Trip
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Created { get; set; }
        public string UserName { get; set; }

        public ICollection<Stop> Stops { get; set; }
    }
}

src/TheWorld/ViewModels/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TheWorld.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        [StringLength(255, MinimumLength = 5)]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(1024, MinimumLength = 5)]
        public string Message { get; set; }
    }
}

src/TheWorld/ViewModels/TripViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TheWorld.ViewModels
{
    public class TripViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255, MinimumLength = 5)]
        public string Name { get; set; }

        public DateTime Created { get; set; } = DateTime.UtcNow;

        public IEnumerable<StopViewModel> Stops { get; set; }
    }
}

src/TheWorld/Controllers/Api/TripController.cs
using AutoMapper;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Net;
using TheWorld.Models;
using TheWorld.ViewModels;

namespace TheWorld.Controllers.Api
{
    [Authorize]
    [Route("api/trips")]
    public class TripController : Controller
    {
        private ILogger<TripController> _logger;
        private IMapper _mapper;
        private IWorldRepository _repository;

        public TripController(IWorldRepository repository, IMapper mapper, ILogger<TripController> logger)
        {
            _repository = repository;
            _mapper = mapper;
            _logger = logger;
        }

        [HttpGet("")]
        public JsonResult Get()
        {
            var trips = _repository.GetUserTripsWithStops(User.Identity.Name);
            var results = _mapper.Map<IEnumerable<TripViewModel>>(trips);

            return Json(results);
        }

        [HttpPost("")]
        public JsonResult Post([FromBody]TripViewModel vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var newTrip = _mapper.Map<Trip>(vm);

                    newTrip.UserName = User.Identity.Name;

                    //save to the database
                    _logger.LogInformation("Attempting to save a new trip");
                    _repository.AddTrip(newTrip);

                    if (_repository.SaveAll())
                    {
                        Response.StatusCode = (int)HttpStatusCode.Created;
                        return Json(_mapper.Map<TripViewModel>(newTrip));
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("Failed to save new trip", ex);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Failed to save new trip");
            }

            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json("Validation failed on new trip");
        }
    }
}

src/TheWorld/Controllers/Web/AppController.cs
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using System.Linq;
using TheWorld.Models;
using TheWorld.Services;
using TheWorld.ViewModels;

namespace TheWorld.Controllers.Web
{
    public class AppController : Controller
    {
        private IMailService _mailService;
        private IWorldRepository _repository;

        public AppController(IMailService service, IWorldRepository repository)
        {
            _mailService = service;
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Trips()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                var email = Startup.Configuration["AppSettings:SiteEmailAddress"];

                if (string.IsNullOrWhiteSpace(email)) ModelState.AddModelError("", "Could not set email, configuration problem.");

                if (_mailService.SendMail(email, email, $"Contact Page from {model.Name} ({model.Email})", model.Message))
                {
                    ModelState.Clear();
                    ViewBag.Message = "Mail Set. Thanks!";
                }
            }
            
            return View();
        }
    }
}

src/TheWorld/Views/App/About.cshtml
@{
    ViewBag.Title = "About Page";
}
<h2>About The World</h2>

src/TheWorld/Views/App/Contact.cshtml
@model TheWorld.ViewModels.ContactViewModel
@{
    ViewBag.Title = "Contact Us";
}
@section Scripts {
  <script type="text/javascript" src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
  <script type="text/javascript" src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<div class="row">

  <div class="col-md-6 col-md-offset-3">
    <h2>Contact</h2>

    <form method="post">
      @if (ViewBag.Message != null)
      { <div>@ViewBag.Message</div> }
      <div asp-validation-summary="ValidationSummary.ModelOnly"></div>

      <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-muted"></span>
      </div>

      <div class="form-group">
        <label asp-for="Email">Email</label>
        <input type="email" asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-muted"></span>
      </div>

      <div class="form-group">
        <label asp-for="Message">Message</label>
        <textarea cols="40" rows="4" asp-for="Message" class="form-control"></textarea>
        <span asp-validation-for="Message" class="text-muted"></span>
      </div>

      <div class="form-group">
        <input type="submit" value="Send Message" class="btn btn-success" />
        <a asp-controller="app" asp-action="Index" class="btn btn-default">Cancel</a>
      </div>
    </form>
  </div>

</div>

src/TheWorld/Views/App/Index.cshtml
@model IEnumerable<TheWorld.Models.Trip>
@{ 
  ViewBag.Title = "Home Page";
}

<div class="row">

  <div class="col-md-12">
    <h1>Welcome to The World</h1>
    <p>This app will allow you to plan for world trips</p>
    <a asp-controller="App" asp-action="Trips" class="btn btn-lg btn-success">View My Trips</a>

  </div>

</div>

src/TheWorld/Views/App/Trips.cshtml
@{ 
  ViewBag.Title = "Home Page";
}

@section Scripts {
  <script type="text/javascript" src="~/lib/underscore/underscore-min.js"></script>
  <script type="text/javascript" src="~/lib/angular/angular.min.js"></script>
  <script type="text/javascript" src="~/lib/angular-route/angular-route.min.js"></script>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=true"></script>
  <script type="text/javascript" src="~/lib/gmaps/gmaps.min.js"></script>
  <script type="text/javascript" src="~/lib/travelmap/travelmap.min.js"></script>

  <environment names="Development">
    <script type="text/javascript" src="~/js/simpleControls.js"></script>
    <script type="text/javascript" src="~/js/app-trips.js"></script>
    <script type="text/javascript" src="~/js/tripsController.js"></script>
    <script type="text/javascript" src="~/js/tripEditorController.js"></script>
  </environment>

  <environment names="Production,Staging">
    <script type="text/javascript" src="~/lib/_app/simpleControls.js"></script>
    <script type="text/javascript" src="~/lib/_app/app-trips.js"></script>
    <script type="text/javascript" src="~/lib/_app/tripsController.js"></script>
    <script type="text/javascript" src="~/lib/_app/tripEditorController.js"></script>
  </environment>
}

<div class="row" ng-app="app-trips">

  <div ng-view></div>

</div>